// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhqaWjR0SAcALJQdLGKJjIavuMAel_6N4',
    appId: '1:260066278496:web:987c4e72ee8478038b1705',
    messagingSenderId: '260066278496',
    projectId: 'kampus-mart-ae6e6',
    authDomain: 'kampus-mart-ae6e6.firebaseapp.com',
    storageBucket: 'kampus-mart-ae6e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATRt2yLh37E3oAYwF03eA8S12b4NmZ72Q',
    appId: '1:260066278496:android:0432782fc3a9f5c18b1705',
    messagingSenderId: '260066278496',
    projectId: 'kampus-mart-ae6e6',
    storageBucket: 'kampus-mart-ae6e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSwn4DyyhQnxkSoM9HBNTGQhN0M9iawDw',
    appId: '1:260066278496:ios:127ca4f86626bae18b1705',
    messagingSenderId: '260066278496',
    projectId: 'kampus-mart-ae6e6',
    storageBucket: 'kampus-mart-ae6e6.firebasestorage.app',
    iosClientId: '260066278496-196412lo8apouv51cdshajdl847oj1o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kampusmart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSwn4DyyhQnxkSoM9HBNTGQhN0M9iawDw',
    appId: '1:260066278496:ios:127ca4f86626bae18b1705',
    messagingSenderId: '260066278496',
    projectId: 'kampus-mart-ae6e6',
    storageBucket: 'kampus-mart-ae6e6.firebasestorage.app',
    iosClientId: '260066278496-196412lo8apouv51cdshajdl847oj1o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.kampusmart2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhqaWjR0SAcALJQdLGKJjIavuMAel_6N4',
    appId: '1:260066278496:web:6f1f25601207a6c48b1705',
    messagingSenderId: '260066278496',
    projectId: 'kampus-mart-ae6e6',
    authDomain: 'kampus-mart-ae6e6.firebaseapp.com',
    storageBucket: 'kampus-mart-ae6e6.firebasestorage.app',
  );
}
